### ISSUE TITLE
Search bar keyboard shortcut

### ISSUE THREAD

**Issue by andrew-hill** [hsoft/moneyguru#387]
Currently (on Mac OS X) the search bar keyboard shortcut is Cmd+Shift+F

As far as I can tell, Cmd+F does nothing, so just wondering why the extra 'Shift' modifier in this shortcut? Usually the addition of option/shift only happens when there's multiple types of search (e.g. an email client, search within current message vs search all messages), so it seems unnecessary.

Workaround is easy—App-specific shortcut via Keyboard pane in System Preferences—but wondering if there's actually a sensible reason for the shift modifier?

**Comment by hsoft** [comment]
moneyGuru doesn't run on MacOS any more.
