### ISSUE TITLE
Make currency-less amount columns slimmer

### ISSUE THREAD

**Issue by hsoft** [hsoft/moneyguru#414]
The fact that amount columns are automatically resized based on contents is really nice, but even when no amount in the table contain a currency, we still reserve space for it, making us over-reserve most of the time.

It's not the end of the world, but I sometimes do split-screen reconciliation and I'm a little tight on horizontal space.

What do you think @brownnrl, easy one?

**Comment by brownnrl** [comment]
Yeah, I think this would be easy.  You want a branch off of develop or master for this?  Develop I would think...

**Comment by brownnrl** [comment]
Now I remember why.  If you don't use that placeholder, you'll get bleed over of an amount into the currency.  See the attached pic.  Though if your amount is that big, you probably aren't too worried about how your money management app handles painting it... :)  So three options

(A)  If you are OK with appearance above where there could be bleed over of those transactions with no non-default currency information while all other currency information is aligned together, then we are done.

![image](https://cloud.githubusercontent.com/assets/672163/5607087/ddb7b4cc-9419-11e4-942c-c3fd52608de2.png)

(B)  If you would prefer to allow resizing, we can compare the ``option.rect`` to the value + currency with + buffer, and then fall back to the default displayed text when there isn't enough room to do the default painting.  This is the method I would prefer, I threw together a quick prototype (will be referenced in a coming commit) and there is a video for it here.  I used some code I was experimenting with in the import ticket.  I cold clean this up have it ready maybe tomorrow.

https://www.youtube.com/watch?v=CVDMMDkQOYk&feature=youtu.be

(C)  Keep the resize to fit, disallow bleeding of currencies and values, and do not use a placeholder.  This would involve querying the model to determine if the table contains any multi-currency amounts in that column.  More complicated, more time, would be deferred until I finish the import work.

**Comment by hsoft** [comment]
I was referring to the case, which happens rather often, where a table would only contain native currencies. That would be your C option.

The A option could be fine too, but I'll admit it looks a bit weird. But then, if an `all_native` flag at the `core.gui` table level ends up being complicated/inefficient, the A option might be better.

**Comment by hsoft** [comment]
The commit referenced above is the kind of fix I had in mind. What do you think?

**Comment by brownnrl** [comment]
Looks really nice, would have taken me a bit to figure out the right places to put the checks for multi-currency.  The only issue I would see is in ensuring that each subclass (or things that might not be subclasses) implement the required method...  If add a schedule item of a native currency and get the following stack trace.  I don't think ``ScheduleTable`` inherits from ``TransactionTable`` but it has amounts to paint.  This might be better served as a mixin to tables?

```
Application Name: moneyGuru
Version: 2.8.2

Traceback (most recent call last):
  File "/home/nelson/projects/moneyguru/qt/support/item_delegate.py", line 145, in paint
    value_painter.paint(painter, value_option, index)
  File "/home/nelson/projects/moneyguru/qt/support/column_view.py", line 139, in paint
    cur_width, val_width = self._getAmountTextWidths(column_data, option)
  File "/home/nelson/projects/moneyguru/qt/support/column_view.py", line 95, in _getAmountTextWidths
    if self._model.all_amounts_are_native:
AttributeError: 'ScheduleTable' object has no attribute 'all_amounts_are_native'
```

**Comment by hsoft** [comment]
The mixin is not a bad idea, because in theory, we could make proper verifications in `AmountPainter` with a simple `isinstance()` check, but that kind of breaks the UI boundary to do so (that kind of check can't be made directly in Cocoa).

In any case a proper implementation *will* have to be made the minute we add Cocoa in the mix, because for Cocoa to call `all_amounts_are_native`, it will need an interface, and we'll have to decide where we put it.

**Comment by brownnrl** [comment]
As a note for "MixIn" style of creating functionality like this, note that I had factored out some functionality from ``TransactionTableBase`` called [``TransactionSelectionMixin``](https://github.com/brownnrl/moneyguru/blob/issue_26_base/core/gui/transaction_table_base.py#L15) because it was required to maintain selections in the ``ImportTable`` even though it didn't inherit from ``TransactionTableBase``.  This is one spot I wanted to attract your attention to for review, and I hadn't yet because it was dwarfed by the base document refactor.  But this seems like a good time to bring it up as its similar to this issue.  If this is a reasonable change for the purposes of the ``ImportTable``, maybe we can make something similar work for amounts.  If it's not, maybe we can identify an alternative for the import ticket.
