### ISSUE TITLE
Stop relying on currency.hardcoded.net

### ISSUE THREAD

**Issue by hsoft** [hsoft/moneyguru#415]
I don't want to have to maintain that server forever. We can query the Bank of Canada and Yahoo directly from moneyGuru.

**Comment by brownnrl** [comment]
Is it possible to post the server code in a separate repo for analysis and for posterity's sake?  I know that is probably still proprietary, and probably isn't too complicated just some XML RPCs right?  But would be interesting to see.  I haven't looked at that portion too closely.

**Comment by hsoft** [comment]
It's at https://bitbucket.org/hsoft/currency_server

**Comment by hsoft** [comment]
Alright, let's do this (after #429). The task is rather simple: take the `fetch_boc_rates` unit from the currency server and implement it as a moneyguru plugin.

Oh, I see that the link I gave earlier is now a 404. Sorry about that, I think I mistakenly erased it recently. I'll git-ify it and push it on github.

As a bonus, I think I'll improve the "Currency Rates" plugin to include the last fetch date so we can more easily debug currency fetching.

**Comment by hsoft** [comment]
https://github.com/hsoft/currency_server
