### ISSUE TITLE
Remember debit/credit column preferences

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#421]
Summary:  Every time the user opens an account tab, he has to do two button presses to change column visibility.  I can see how that would be annoying.

Detailed:
From the forum member ColinT,

```
moneyGuru is great (I should stop at this point, shouldn't I?) at remembering which tabs are open, column order, preferences, etc.

However, I'm one of the (rare?) people who prefer to use Debit and Credit instead of Increase and Decrease. As someone with an accounting background, I can't get my head around decreasing my bank account and decreasing my credit card balances in the same transaction (for instance).

However, I need to select Debits & Credits every time I open a new tab of a specific account, and if I close the software and open it again later, I need to select Debits & Credits again for EACH account tab.

Since all the other preferences are remembered, I'm guessing this is a glitch/oversight. Can anyone help sort it out? Perhaps I'm doing something wrong?

(Long-time user of moneyGuru, back after an 18-month break, following a motherboard failure.)
```

I've never paid much attention to that button before, that's actually a nice feature.  :)

So I would think the formal statement would be...

"For each Table type, remember the last column visibility selection (at least at the account level) and use that visibility setting at creation of new tabs..."

Definitely in the "thinking" category right now.

**Comment by hsoft** [comment]
I label it as a feature, but it's probably a bug. I know for sure that column visibility is supposed to be remembered under OS X. I can't remember whether it was ever implemented for Qt, but I would tend to say yes.

**Comment by ColinT1970** [comment]
May I add that this *IS* a bug. All of the other options on "that button" are global and remembered between sessions. The Debit & Credit preference was likewise until sometime during my 18-month time away from computers. Now it needs to be selected on opening each account tab. If tabs are left open on quitting, on restarting those tabs have reverted to Increase & Decrease and the option needs selecting for each open tab individually as well as any new tabs.

**Comment by hsoft** [comment]
Yeah, I can reproduce it under Qt. It's specific to Debit/Credit columns though (I'll change the title). As @ColinT1970 says, it's a bug.

**Comment by hsoft** [comment]
It's fixed now and will be part of the 2.10 release. It's a bit embarrassing that this bug took so long to fix, but such are things with scarcely used features.

**Comment by ColinT1970** [comment]
A HUGE thank you!

I feared I may be the only one who uses this feature (given I originally requested it) and feared it may NEVER be fixed.

As has been noted, it WAS incredibly frustrating to select the button and Debit/Credit every single time I opened an account (or for each account when I restarted a saved session) and I am so incredibly grateful to you for spending time (and having the ability) to locate and correct the bug. And now I look forward to the 2.10 release with great anticipation.

Very much obliged indeed.

Kind regards


Colin

**Comment by ColinT1970** [comment]
As I've been using the 2.10 release for a while now, I just wanted to add to my thanks regarding the above. I'd been tolerating the malfunction and it really did give me a headache. Every time I open an account tab or print a report, I'm delighted I don't need to remember to change anything! It also avoids any confusion for me, since funds going into an account aren't always in the same increase or decrease column: e.g. paying off a credit card is a decrease, but adding to savings is an increase, yet the money is going into that account in both instances. (I know, accountant-types! ;-) )
