### ISSUE TITLE
Menu/Icons missing for master branch

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#439]
I was getting my local machine back to a state to start dev on the ``master`` branch, and I noticed that there is no main menu or icons in the lower toolbar for Qt ui / python3.4 / Ubuntu 14.04.  ``maint-2.9`` still shows the main menu and lower toolbar icons, so I was curious if this was a mid-state transition into Qt5?

This could be a local configuration issue, I haven't touched it for a bit.

![screenshot - 07162015 - 09 45 26 pm](https://cloud.githubusercontent.com/assets/672163/8738988/0596ff34-2c04-11e5-889c-4a5b14d98f16.png)

**Comment by hsoft** [comment]
Might it be cause you don't have `pyrcc5` installed? I think that the build doesn't fail when it's not installed (which it should probably do)

**Comment by brownnrl** [comment]
I did not have ``pyrcc5`` installed.  Installing fixed the icons, but not the main menu.  Any other quick thoughts before I dive further in?

**Comment by brownnrl** [comment]
Hmmm... I think this is pyqt5 and xubuntu specific behavior (or at least my local setup).  Created a simple single file example of a menu and it didn't appear.

**Comment by hsoft** [comment]
If it's like with GNOME, yeah, the main menu disappears for UI-slickness reasons. Firefox also hide its menu on my system. I can toggle its visibility by pressing ALT.

**Comment by brownnrl** [comment]
I'm not even sure what it is, but removing a package called ``appmenu-qt5`` fixed the issue of the missing menu.  Last comment on the bug tracker linked below.

https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619

Up to you about leaving this ticket open to close out the check for ``pyrcc5`` availability within the ``build.py`` script?

**Comment by hsoft** [comment]
yes, I think the build script should fail if pyrcc isn't there.
