### ISSUE TITLE
Can't get account back into capital overview

### ISSUE THREAD

**Issue by jicho** [hsoft/moneyguru#443]
Hi,

When I look at the account details (CMD + I) after selecting one in the capital overview and change the type into, for example, "income" (the Dutch version "inkomsten") I don't see it anymore in the capital overview :(

I've found that I can switch to the account using CMD + SHIFT + A, but... once that is done there is no way (as far as I see) to set the type of the account (back) so I will be visible again under activa or passiva.

Did I found a bug? Or am I doing something wrong during my MoneyGuru test-drive?

Thanks for the reaction.

**Comment by hsoft** [comment]
The "Net Worth" views lists only assets and liabilities. When the account is an income or expense, it's listed in "Profit & Loss" view.

**Comment by jicho** [comment]
Ah, found it :)

Thanks!
