### ISSUE TITLE
Writing out files raises FileNotFoundError

### ISSUE THREAD

**Issue by AndrejAleksic** [hsoft/moneyguru#445]
Standard Save works "td_bank.moneyguru", but when "save as" or export of any type is atempted, FileNotFoundError is returned. 
Naturally the target path does not exist because I want to write a new file.

``` python.traceback
Application Name: moneyGuru
Version: 2.9.3

Traceback (most recent call last):
  File "/home/kinleyage/sandbox/moneyguru/qt/controller/document.py", line 109, in saveAs
    self.model.save_to_xml(docpath)
  File "/home/kinleyage/sandbox/moneyguru/core/document.py", line 1210, in save_to_xml
    self.transactions, self.schedules, self.budgets
  File "/home/kinleyage/sandbox/moneyguru/core/saver/native.py", line 119, in save
    fp = open(filename, 'wt', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: "('/home/kinleyage/sandbox/moneyguru_doc/td_bank.moneyguru.15aug.backup.moneyguru', 'moneyGuru Documents (*.moneyguru)').moneyguru"
```

Just as additional info, the original file does exists, and I am cpable of writing to it.

```bash
┌┌(kinleyage@kinleytpad)┌(543/pts/6)┌(10:08pm:09/07/15)┌-
└┌(%:~)┌- ls -ali /home/kinleyage/sandbox/moneyguru_doc/
2244825 drwxr-xr-x 3 kinleyage kinleyage   4096 Sep  7 21:47 .
2241171 -rw-r--r-- 1 kinleyage kinleyage 158560 Sep  7 22:01 /home/kinleyage/sandbox/moneyguru_doc/td_bank.moneyguru
```
Nontheless, I can still manually copy the original file in order to make backups.

**Comment by ancientHacker** [comment]
I can't reproduce this on Mac.  I suspect it should have the qt label.

**Comment by hsoft** [comment]
True, this is probably qt-specific

**Comment by ancientHacker** [comment]
I can't repro this in Mac/QT either.  Perhaps this has to do with the fact that he has automatic backups set up.  I'll try repro-ing it that way. -d.

**Comment by hsoft** [comment]
I'd be surprised if it had anything to do with autosaves

**Comment by hsoft** [comment]
This crash is reproducible by manually entering a path for a destination filename for which the enclosing folder doesn't exist. For example, if I enter `~/doesnotexist/foo.moneyguru`, I'll get the crash.

I don't see any other way to reproduce the crash than by manually typing a directory name as part of the destination name.

@AndrejAleksic is that what happened for you?
