### ISSUE TITLE
How to create own custom currency rate?

### ISSUE THREAD

**Issue by AlexMiller77** [hsoft/moneyguru#452]
Hello
I read this https://www.hardcoded.net/moneyguru/help/en/currencies.html#custom-currencies but I cant understand how to create own custom currency rate? Because in your country national currency rate is not correct. In all transaction I need to write down custom currency rate.

Thank you for answer

**Comment by hsoft** [comment]
Having a custom currency rate for a supported currency? There's no reason to do that unless the rate you get is bad, but it normally shouldn't be.

What's the currency you're using and what rate do you get for what date?

**Comment by AlexMiller77** [comment]
I use USD, UAH and RUB . This currency is supported. 
I need to create custom rates, because http://joxi.ru/EA4bpjKSDvyjym this is not normal Ukrainian rate to dollar.
in real life 1 USD = 27.2 UAH
in software 1 USD = 24,5 UAH

**Comment by AlexMiller77** [comment]
Hello!
Thank you for answer! This is my issue https://github.com/hsoft/moneyguru/issues/452 <https://github.com/hsoft/moneyguru/issues/452>

С уважением,

Алекс Миллер 
alex@alexmillerpost.com <mailto:alex@alexmillerpost.com>
alexmillerpost.com <http://alexmillerpost.com/>

**Comment by AlexMiller77** [comment]
Having a custom currency rate for a supported currency?
- I need to create for each transaction on currency rate. I dont know how. 

p.s.

This is very important to me because I fell in love with gurumoney

**Comment by hsoft** [comment]
According to google ( https://www.google.ca/search?q=uah+to+cad&ie=utf-8&oe=utf-8&gws_rd=cr&ei=QXGdVtm-CoemjgTp9KrYBQ#q=usd+to+uah ), USD/UAH rate for today is 24.6, so it seems that moneyGuru's rate is good.

Of course, it's the market rate, not the "street rates". But exchange rates are only used for approximations of values, so it's not such a big deal. When you actually convert money through a transaction, you can use whatever rate you want.

moneyGuru doesn't have custom rate capabilities. The only way to achieve that is through plugins which you have to code yourself.

**Comment by AlexMiller77** [comment]
Yes, MG rate is good. But street rate is another. Too bad. Because its very important for me. For example I have I have 2 accounts: 
1 - USD
2 - UAH

if I create transaction 100 USD -> UAH
Balance in GM will be 2460 UAH, but real balance must be 2720. I lose 270 UAH on one hundred dollars! I dont know how to avoid this problem in GM. Because I want to continue use this program.

**Comment by hsoft** [comment]
If you create a transaction, then it has to be a [Multi-currency transaction](https://www.hardcoded.net/moneyguru/help/en/currencies.html#multiple-currencies-transactions) and then exchange rates don't matter. Exchange rates are *only* used when estimating value, never for transactions themselves.

So, if for example you have 100 USD in your hand and go exchange it in the streets for 2720 UAH, then just create a new transaction with a 100 USD split and a 2720 UAH split. This will work even if the currency rate if 24.6

**Comment by fokusov** [comment]
This problem i have too. And my transaction look like that 
![image](https://cloud.githubusercontent.com/assets/517740/12413604/37f08880-bea1-11e5-8f2f-e4593443320a.png)

**Comment by AlexMiller77** [comment]
Thank you! You save my life
