### ISSUE TITLE
show info crash!!!! 2.10.0

### ISSUE THREAD

**Issue by reddot15** [hsoft/moneyguru#456]
**how to recreate, go to schedules-->select an entry-->show info**

```
Application Name: moneyGuru
Version: 2.10.0

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/controller/main_window.py", line 529, in editItemTriggered
    self.model.edit_item()
  File "/usr/share/moneyguru/core/gui/main_window.py", line 346, in edit_item
    return self._perform_if_possible('edit_item')
  File "/usr/share/moneyguru/core/gui/main_window.py", line 188, in _perform_if_possible
    return getattr(current_view, action_name)()
  File "/usr/share/moneyguru/core/gui/schedule_view.py", line 48, in edit_item
    schedule_panel.load()
  File "/usr/share/moneyguru/core/gui/base.py", line 310, in load
    self.view.post_load()
  File "/usr/share/moneyguru/qt/controller/panel.py", line 125, in post_load
    self._connectSignals()
  File "/usr/share/moneyguru/qt/controller/panel.py", line 60, in _connectSignals
    self._signalMapper.mapped[QWidget].connect(self.widgetChanged)
KeyError: 'there is no matching overloaded signal'
```

**Comment by reddot15** [comment]
update: All tabs are affected.

**Comment by hsoft** [comment]
@reddot15 what system are you on? I can't reproduce the issue here, whether it's with `ctrl+i`, the `i` button or the menu button, they all invoke the dialog properly.

... oh, I see. On Ubuntu, there's the crash.

**Comment by reddot15** [comment]
linux mint 17.2 mate x64

**Comment by hsoft** [comment]
Hum, I'm puzzled by this problem. It's certainly caused by the conversion to Qt5, but that `QWidget` overload *should* work (because it does on my system). My only guess so far would be that this is caused by PyQt5's version, which on 14.04 is a bit old (5.2.1).

I'll look at this later, but for now I'll just remove the build from the PPA, since it's so broken. Thanks for the heads up!

**Comment by hsoft** [comment]
I've just tried with Ubuntu 15.10 and I can't reproduce the issue. So I guess it's a matter of an unmet minimal PyQt5 version.

@reddot15 what version of PyQt5 do you have on your system?

**Comment by reddot15** [comment]
hey!!! thanks for your help. i also have (5.2.1+dfsg-1ubuntu1) so i guess i just need to update PyQt5. ???

**Comment by hsoft** [comment]
I think so. I'd be curious to know if that works for you.

**Comment by vknecht** [comment]
I'm hitting the same issue on Ubuntu 14.04 (can't update for now) and Moneyguru 2.10.1.
It seems the 2.9.4 package isn't available anymore so there's no fallback :-(

**Comment by hsoft** [comment]
@vknecht you get this error with the same reproduction steps, on 14.04 and MoneyGuru 2.10.1?

**Comment by vknecht** [comment]
Yes

**Comment by hsoft** [comment]
It took a while, but I finally found the time to reproduce the issue @vknecht is mentioning. The crash indeed happens under Ubuntu 14.04.

It doesn't happen on my main system though.

**Comment by vknecht** [comment]
@hsoft It works, thank you !
