### ISSUE TITLE
Version 2.10.0 is not opening… immediate crash!

### ISSUE THREAD

**Issue by gryphonent** [hsoft/moneyguru#458]
Glad to see continued development on one of my favourites and most used apps. However, version 2.10.0 doesn’t open at all. It constantly crashes reporting that “moneyGuru cannot be opened because of an error.”

**Comment by hsoft** [comment]
Hi @gryphonent , are you still on OS X? Is there anything showing in the Console?

**Comment by hsoft** [comment]
Oh, nevermind. I made a mistake during the OS X build process. Darnit! Fixing...

**Comment by hsoft** [comment]
Oh, and it's not even trivial to fix :( I'm angry after myself for this sloppy release. I'm reverting OS X to v2.9.4 until I sort this out. Thanks for the warning.

**Comment by hsoft** [comment]
@gryphonent everything should be fine now. If you re-download moneyGuru 2.10.0 or re-update from 2.9.4, it should work. Could you confirm that it does?

**Comment by gryphonent** [comment]
Hi Virgil, thanks for the swift fix. Yep, I’m still on Mac OS X… nowhere else to go for me after 30 years with Apple…:) The latest build works just fine.

**Comment by hsoft** [comment]
great!
