### ISSUE TITLE
Bold figures set low

### ISSUE THREAD

**Issue by ColinT1970** [hsoft/moneyguru#459]
Wherever bold text/figures appear within moneyGuru, they are set "low" on the line. I anticipate this is a bottom-align within a cell, rather than vertically-centred align, as is seemingly the case with the plain text.

To see what I mean, look at the total row of any report/account or see the End column of Net Worth or Current Column of Profit & Loss.

This is also the case when printing, sometimes causing the bottom of the text/figures not to print.

It wasn't always this way, I'm guessing just a minor alteration somewhere, given it's so global.

**Comment by hsoft** [comment]
Which OS do you use?

**Comment by ColinT1970** [comment]
OS X El Capitan Version 10.11.4

(A HUGE thanks again for sorting out debit/credit preference!)

**Comment by hsoft** [comment]
I'm not very well equipped mac-wise and I don't have access to many versions of OS X. I'm also on 10.11 so I can probably reproduce the bug the next time I fire up my mac mini, but meanwhile, could you verify if the bug is linked to 10.11? I mean: Does the same bug happen if we run moneyGuru on 10.0 or lesser?

**Comment by ColinT1970** [comment]
I'm not able to confirm, I'm afraid. I think it has been around for a while. Would a PDF or screenshot help?

To give an indication, comma separators lose their "tails" and look like decimal points or separators.

**Comment by ColinT1970** [comment]
A big thank you, Virgil! This wasn't a great hardship, but it's  definite improvement. I'm very grateful to you.


Colin
