### ISSUE TITLE
Windows? Serious?

### ISSUE THREAD

**Issue by cvladan** [hsoft/moneyguru#463]
Are you serious?
Really?
Dropping Windows support?

I assume that you conducted a small survey somewhere (Google+, Facebook?) how much users are using moneyGuru on Windows? Have you checked Google Analytics to see percentages of users visiting moneyGuru page? If that is less than 30%, then I support you decision.

By the way, I am normally using moneyGuru on Windows 10 since the introduction of latter.

**Comment by hsoft** [comment]
This decision has nothing to do with usage, it has to do with my unwillingness to work with Windows. If there was someone stepping up to maintain the Windows version, we wouldn't have to drop it.
