### ISSUE TITLE
An empty Untitled document is always opened along with the chosen document (MacOS X)

### ISSUE THREAD

**Issue by stysedo** [hsoft/moneyguru#467]
I don't know anything about software development or coding, so please forgive me if this bug report is lacking in some way...
When opening our chosen moneyGuru document to launch moneyGuru an empty Untitled document is also shown. This seem to be related to the MacOS X System Preference of: System Preferences -> General -> Close windows when quitting an app. With that pref enabled (which is the default state for MacOS X 10.11.6) we get the empty document when opening a moneyGuru document to launch moneyGuru.
moneyGuru seems to be the only app that I have that exhibits this behavior of opening a new empty document when a chosen document is opened.
MacOS X 10.11.6 (also present under 10.9.5) moneyGuru 2.10.2 (and earlier)

**Comment by datguy** [comment]
I tried to recreate this on macOS Sierra (10.12.4) and moneyGuru 2.10.2 (built from source on 5/27), but I did not get the empty document described above.

**Comment by hsoft** [comment]
moneyGuru doesn't run on Mac OS any more.
