### ISSUE TITLE
"negative" or "inverse" mode for liabilities

### ISSUE THREAD

**Issue by thenaterhood** [hsoft/moneyguru#470]
My bank exports my credit card transations as deductions from my credit limit rather than increases to my balance. As far as I'm able to tell, MoneyGuru expects the opposite, so I'm required to go through and negate all my credit transactions after I've imported them from that particular bank if I want them to be treated correctly. I doubt that mine is the only bank that handles it this way.

An option to negate all the incoming transactions on the import screen would be super helpful.

**Comment by hsoft** [comment]
It's already possible. There's a "Invert amounts" item in the "Are some fields wrong?" section. Or are we talking about something else?

**Comment by thenaterhood** [comment]
You are totally correct, and I don't know how I missed that. Closing because PEBKAC :)
