### ISSUE TITLE
Printing Net Worth & Profit Loss tabs

### ISSUE THREAD

**Issue by hsmoon1** [hsoft/moneyguru#482]
Any amount larger than $999 has part of the thousands column that doesn't print and no columns of greater amounts print. I realize windows version is no longer supported but could a fix be done so those tabs can be printed as reports? Windows 8.1, MoneyGuru 2.9.4
I'm a user, not a developer, and have no idea what/how to do it myself.
Your program is the slickest little accounting/bookkeeping package of any I've tried, and I've tried/used many. Really too bad it's no longer supported.

**Comment by hsoft** [comment]
I can't reproduce the problem on a modern linux system. I'm sorry to say that Windows ever seeing a new moneyGuru release is very unlikely. I'm closing this.
