### ISSUE TITLE
Import UTF-16 files

### ISSUE THREAD

**Issue by mortomanos** [hsoft/moneyguru#486]
Hi Virgil,
unfortunately my bank switched from iso to utf-16 encoding when generating CSV files. But moneyguru only handles utf-8 encoding correctly. Will you be able to add this feature?
Regards,
Michael

**Comment by hsoft** [comment]
Yes, it would be trivial to add. It would also be a good opportunity for someone looking for an easy first ticket.

**Comment by mortomanos** [comment]
I assume it has to be in core/loader/base ?

**Comment by hsoft** [comment]
`SUPPORTED_ENCODINGS` should do it.

**Comment by hsoft** [comment]
@mortomanos it turns out it wasn't trivial to implement after all, but it's done! Will be present in an upcoming 2.11 update.
