### ISSUE TITLE
Strange display of decimal numbers

### ISSUE THREAD

**Issue by ppmt** [hsoft/moneyguru#501]
I just installed the Xenial version of moneyguru on my fresh install on 18.04 (cosmic) and I have a strange behaviour regarding the display of some numbers

Most of the number in my statement appears correctly but some of them will display only some portion of it. For example instead of "9.54" I will see "9." 
or instead of "1,356.56" I will see "1,"
The calculation seems correct and if I double click the entry the digit will be correct.

It is quite random and seem to affect number bigger that 1000 or lower than 10

**Comment by hsoft** [comment]
I experience the problem as well. It seems to be related to a recent Qt update.

**Comment by hsoft** [comment]
Yes, because I haven't released a new version yet.
