### ISSUE TITLE
Version 2.13.1 won't compile on Ubuntu 18.10

### ISSUE THREAD

**Issue by ppmt** [hsoft/moneyguru#509]
Hello,
Not sure if we can write issue on the latest version but I thought I would try.

I have downloaded the zip file and installed the requirement but when I run the command make I get all kind of errors. Since I don't know anything about C I am not sure what to make of it.

I have attached the error file I get. Is it supposed to work on Ubuntu 18.10?

[moneyguru_error.zip](https://github.com/hsoft/moneyguru/files/2866085/moneyguru_error.zip)

PS: I am glad that you found a renewed interrest in working on MoneyGuru :+1:

**Comment by hsoft** [comment]
I hadn't tried building moneyguru on an ubuntu environment yet. Now that I have, I see multiple problems that need to be addressed in the README:

1. `glib2.0-dev` is needed
2. `gettext` is needed
3. `make PYTHON=python3` has to be called because, even if python 2 isn't installed by default, `python` still points to py2 when installed and doesn't exist when not.

I would advise a `make clean` followed by `make PYTHON=python3`.

**Comment by ppmt** [comment]
point 1 and 2 wre already install on my laptop but point 3 did fix it!

I can now run the latest version of MG :)

Looks great!

**Comment by systemocracy** [comment]
I had the same issue in Solus make PYTHON=python3 did the trick.
Had some other minor issues. Here's the full install did not troubleshoot the path issue:
Dependencies: 
`sudo eopkg it -c system.devel`
`sudo eopkg it sqlite3-devel python3-devel python-qtpy`
Build and run:
`make PYTHON=python3 `
`make run`
Then had a couple of issues to install. It tries to install on /usr/local/ on Solus uses/usr/:
`PREFIX=/usr; export PREFIX`
`sudo -E bash -c 'make install'`
This installed the app in the desktop, however it did not set an icon:
`cat /usr/share/applications/moneyguru.desktop 
[Desktop Entry]
Encoding=UTF-8
Name=moneyGuru
Comment=Personal finances management application.
Exec=moneyguru
Icon=${PIXMAP}
Terminal=false
Type=Application
Categories=Qt;Office;Finance`
Had to change `Icon=${PIXMAP}` to `Icon=moneyguru` as the icon png was already installed in the pixelmap folder.

**Comment by ppmt** [comment]
The install sort of worked for me. I don't the error matters much but here is what I had.
```
sudo make install 
Build complete! You can run moneyGuru with 'make run'
python3 -m compileall core qt
Listing 'core'...
Listing 'core/gui'...
Listing 'core/loader'...
Listing 'core/model'...
Listing 'core/model/currency_provider'...
Listing 'core/saver'...
Listing 'core/tests'...
Compiling 'core/tests/__init__.py'...
...
Listing 'qt/print_'...
Listing 'qt/support'...
./support/install.sh "" "/usr/local" "/usr/local/lib/moneyguru" "/usr/local/share/moneyguru"
cp: cannot stat 'core/plugin': No such file or directory
make: *** [Makefile:86: install] Error 1
```
```
$ which moneyguru 
/usr/local/bin/moneyguru
```
```
/usr/local/bin$ ls -alrt moneyguru
lrwxrwxrwx 1 root root 31 Feb 15 09:52 moneyguru -> /usr/local/lib/moneyguru/run.py
```
