### ISSUE TITLE
Understanding Automatically place decimal when typing (v 2.13.1)

### ISSUE THREAD

**Issue by ppmt** [hsoft/moneyguru#510]
Just installed latest version of MG and I wonder if I am reading that preference the wrong way
When it is ticked and I enter 10 then the number recorder is 0.10
When it is unticked and I enter 10 then the number recorder is 10.0

Somehow in my brain it seems counter intuitive!

PS: also each time I modified a preference the active account windows becomes very small and I need to get out of it to get it back to its normal size.

**Comment by brownnrl** [comment]
I think it's for quick editing.  So if I want an amount equal to "1000.01" I can type "100001" and avoid typing the decimal.  I would assume this is for people who always enter some cent amount and probably have many such transactions.

**Comment by ppmt** [comment]
Ah!!! I see 

Yes it makes sense when interpreted like that :)

I will close the issue then
