### ISSUE TITLE
Build fails, seemingly in py_ccore.c?

### ISSUE THREAD

**Issue by GDroulers** [hsoft/moneyguru#511]
Hi, I am a long term Mac user of the software. I am switching to linux mint and ran into trouble during build.

I am fairly new to linux and when I tried to build with makefile I got Glib error and then a python version error. That fixed, I now get the attached traceback log. I can't find why. I attach the log, y system info and my python package lists (Python 2.7 and 3.6 are installed on my system)
[MakeFileErrorLog_20190314.txt](https://github.com/hsoft/moneyguru/files/2968645/MakeFileErrorLog_20190314.txt)
[PythonPackageLists_20190314.txt](https://github.com/hsoft/moneyguru/files/2968646/PythonPackageLists_20190314.txt)
[SystemINFO_20190314.txt](https://github.com/hsoft/moneyguru/files/2968647/SystemINFO_20190314.txt)

Can anyone help me here?

Thanks

**Comment by hsoft** [comment]
Here's your problem: `-I/usr/include/python2.7`. I don't know why you end up with that, though.

**Comment by GDroulers** [comment]
OK. Do you expect this part to be there but with a version that matches requirements (i.e. 3.6 in my case) or is it that it is unexpected to have this in there. I can't find where this line gets called in the main makefile or in the ccore makefile. As I said, I am quite new to linux although I have some programming knowledge and could try to debug with some pointers.

**Comment by hsoft** [comment]
Did you try to build the `2.13.1` tag? There's been numerous build system improvement lately. Does the newly tagged `3.0.0` build better?

**Comment by GDroulers** [comment]
I will try it at some point, just been too busy with work lately. Thanks
for looking! Will post back if it works.

Gabriel
Sent from my mobile phone

Le sam. 6 avr. 2019 16 h 13, Virgil Dupras <notifications@github.com> a
écrit :

**Comment by GDroulers** [comment]
Build 3.0.0 actually succeeded. The command to make sure all packages were installed was also more complete in this build (from the readme).
Thanks! I can start accounting again!
