### ISSUE TITLE
CSV File Target Selection doesn't carry to import screen

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#513]
While checking to see if an import bug in 2.13.1  involving binding dates forward and backward in time against existing transaction presented itself in 3.0.0 (it did not), I noticed that if you select a target account in the CSV file importer, the account entries from the target account appear, but the target account combo selector on the import window remains at the default entry prompting the user to select an account.  Not re-selecting the correct account at the import window (which if done resets all the bindings), results in the stack trace below once import is selected.

```
Application Name: moneyGuru
Version: 3.0.0

Traceback (most recent call last):
  File "/home/nelson/projects/moneyguru/qt/controller/import_/window.py", line 137, in targetAccountChanged
    self.model.selected_target_account_index = index
  File "/home/nelson/projects/moneyguru/core/gui/import_window.py", line 397, in selected_target_account_index
    self.selected_pane.selected_target = target
AttributeError: 'NoneType' object has no attribute 'selected_target'
```

**Comment by hsoft** [comment]
Thanks, does it work better with the commit above?

**Comment by hsoft** [comment]
I will suppose that it does and release 3.0.1

**Comment by brownnrl** [comment]
Sorry, I was on travel, it does work now.
